### ISSUE TITLE
Compatibility with Elixir 1.9.x

### ISSUE THREAD

**Issue by joshuataylor** [exponentially/extreme#64]
So Elixir 1.9 is out! :tada:

Seeing the following when trying to compile with 1.9 (using the latest github):

```
==> extreme
Compiling 13 files (.ex)

== Compilation error in file lib/messages.ex ==
** (ArgumentError) argument error
    :erlang.++("event_store", ".proto")
    src/gpb_lib.erl:788: :gpb_lib.copy_filename_ext/2
    src/gpb_parse.yrl:489: anonymous fn/2 in :gpb_parse.shorten_file_paths/1
    (stdlib) lists.erl:1239: :lists.map/2
    src/gpb_parse.yrl:486: :gpb_parse.shorten_file_paths/1
    src/gpb_parse.yrl:457: :gpb_parse.post_process_all_files/2
    lib/exprotobuf/parser.ex:22: Protobuf.Parser.finalize!/2
    lib/exprotobuf.ex:152: Protobuf.parse/2
could not compile dependency :extreme, "mix compile" failed. You can recompile this dependency with "mix deps.compile extreme", update it with "mix deps.update extreme" or clean it with "mix deps.clean extreme"
```

However, running `mix compile` in a cloned version of extreme works.

**Comment by burmajam** [comment]
Hi @joshuataylor. 0.13.4 version is just published to hex. Can you please check it?

**Comment by slashdotdash** [comment]
I've just encountered the same compile error with extreme v0.13.4 (for both Elixir 1.9.0 and 1.8.2). 

The issue is caused by either `exprotobuf` or `gpb`. Downgrading `exprotobuf` to the previous release (v1.2.9), as shown below, works around the problem (including for Elixir v1.9.0). 

```elixir
# mix.exs
def deps do
  [
    {:extreme, "~> 0.13"},
    {:exprotobuf, "== 1.2.9"}
  ]
end
```

**Comment by slashdotdash** [comment]
Linking the following two PRs for `exprotobuf` and `gpb` to fix the problem:

- [Use Erlang's ++ to concatenate string will affect the compatibility for Elixir #167](https://github.com/tomas-abrahamsson/gpb/pull/167)
- [Adapt for gpb ~> 4.7.1 #105](https://github.com/bitwalker/exprotobuf/pull/105)

**Comment by joshuataylor** [comment]
Thanks so much for submitting a PR to gpb @slashdotdash :) :tada:

**Comment by slashdotdash** [comment]
@joshuataylor I can't take the credit for those PRs, I only found them!

**Comment by burmajam** [comment]
Thanks for pointing to the problem and solution guys. I think we should wait for fix in `exprotobuf` that @slashdotdash referenced to. In the meantime I'll leave this issue opened just in case someone else has the same problem

**Comment by jg-made** [comment]
JFYI the `exprotobuf` and `gpb` PRs linked above are merged and closed, respectively.
